# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Libre Objet
email: hello@libreobjet.org
moto: > #
  We design, modify and use objects,<br>
  and you can be one of us.
description: > #
  A curated list of libre objects.
  A collective of industrial designers and artists sharing a common question around open source design, processes and products.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://libreobjet.org" # the base hostname & protocol for your site
twitter_username: libreobjet
github_username:  libreobjet

# Build settings
markdown: rdiscount #redcarpet #kramdown

exclude: ['node_modules', 'Gruntfile.js', 'package.json', '**/*.styl', 'README.md']
keep_files: ['.git', 'README.md']

# Object collection
collections:
  objects:
    output: true

# Default values
defaults:
  - scope:
      path: ""
      type: objects
    values:
      layout: object
