# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Libre Objet
email: hello@libreobjet.org
moto: > #
  We design, modify and use objects,<br>
  and you can be one of us.
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://libreobjet.org" # the base hostname & protocol for your site
twitter_username: libreobjet
github_username:  libreobjet

# Build settings
markdown: kramdown

exclude: ['node_modules', 'Gruntfile.js', 'package.json', '**/*.styl']
keep_files: ['.git']

# Object collection
collections:
  objects:
    output: true

# Default values
defaults:
  - scope:
      path: ""
      type: objects
    values:
      layout: object
